import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
    const [ingredient, setIngredient] = useState('');

  const addIngredient = async () => {
    await fetch(`/api/ingredients`, {
      method: "POST",
      body: JSON.stringify({ title: ingredient }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    await router.push("/ingredientes");
  }

  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 2</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="form-group">
          <label htmlFor="title">Ingrediente:</label>
          <input
            type="text"
            className="form-control my-3"
            id="title"
            placeholder="Ingrediente"
            value={ingredient}
            onChange={(e) => setIngredient(e.target.value)}
          />
        </div>
        <button type="submit" className="btn btn-primary" onClick={addIngredient}>
          Agregar
        </button>
      </main>
    </>
  );
}
