import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [ingredients, setIngredients] = useState([]);
  useEffect(() => {
    fetchIngredients();
  }, []);

  const fetchIngredients = async () => {
    const result = await fetch("/api/ingredients");
    const ing = await result.json();
    setIngredients(ing);
  };

  const handleDelete = async (id) => {
    await fetch(`/api/ingredients/${id}`, {
      method: "DELETE",
    });

    await fetchIngredients();
  };

  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 2</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="buttons my-3">
          <button className="btn btn-info" onClick={() => {
            router.push('/ingredientes/agregar')
          }}>Agregar Ingrediente</button>
        </div>
        <table className="table table-striped">
          <thead>
            <tr>
              <th>Ingrediente</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {ingredients.map(({ id, title }) => (
              <tr key={id}>
                <td>{title}</td>
                <td>
                  <button
                    className="btn btn-success"
                    onClick={() => {
                      router.push(`/ingredientes/${id}`);
                    }}
                  >
                    Modificar
                  </button>{" "}
                  <button
                    className="btn btn-danger"
                    onClick={() => {
                      handleDelete(id);
                    }}
                  >
                    Eliminar
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
}
