import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 2</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="input-group mb-3 mt-3">
        asdasd
      </div>
      </main>
    </>
  )
}
