import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

export default function Home() {
  const router = useRouter();
  const [platillo, setPlatillo] = useState({});
  const [status, setStatus] = useState("disabled");
  useEffect(() => {
    if (router.isReady) {
      fetchPlatillo();
    }
  }, [router.isReady]);

  const fetchPlatillo = async () => {
    const id = router.query.id;
    if (id) {
      const result = await fetch(`/api/platillos/${id}`);
      const ing = await result.json();
      if (ing) {
        setPlatillo(ing);
      }
    }
  };

  const handleEdit = () => {
    if (status === 'disabled') {
      setStatus('enabled');
    } else if (status === 'enabled') {
      updatePlatillo();
    }
  }

  const updatePlatillo = async () => {
    await fetch(`/api/platillos/${platillo.id}`, {
      method: "PUT",
      body: JSON.stringify({ title: platillo.title }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    await router.push("/platillos");
  }

  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 2</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container my-3">
        <h1>Información:</h1>
        <div className="form-group">
          <label htmlFor="title">Nombre:</label>
          <input
            type="text"
            className="form-control my-1"
            id="title"
            value={platillo.title}
            onChange={(e) => setPlatillo({
              id: platillo.id,
              title: e.target.value
            })}
            disabled={status === 'disabled'}
          />
        </div>
        <button type="submit" className="btn btn-primary" onClick={handleEdit}>
          {
            status === 'disabled' ? 'Editar' : 'Guardar'
          }
        </button>
      </main>
    </>
  );
}
